---
title: "project-1-final"
author: "Rohith Kanakagiri"
date: "28/10/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data preprocessing
```{r}
library(readxl)
library(dplyr)
library(corrplot)
library(ggplot2)
library(tidyr)

#The data was downloaded as a .data file which was imported into excel to change to a xls file and imported as a data set into R

german_data <- read_excel("german data.xlsx")

#Adding Column appropriate column names to the data file

colnames(german_data) = c("Checking_Account","Duration","Credit_History","Purpose","Credit_Amount","Savings_Account","Present_Employement","Installment_Rate","Personal_Status","Guarantors","Residence_Since","Property","Age","Other_Installment_Plan","Housing","Existing_Credit","Job","Dependents","Telephone","Foreign_Worker","Good_bad")

#converting the cost matrix into Good and Bad risk description
german_data$Good_bad[german_data$Good_bad == 2] <- "Bad"
german_data$Good_bad[german_data$Good_bad == 1] <- "Good"

#adding a new column Gender and using the categorical data to add values to it the new column
german_data$Sex[german_data$Personal_Status == "A91" | german_data$Personal_Status == "A93" | german_data$Personal_Status == "A94"] <- "M"
german_data$Sex[german_data$Personal_Status == "A92" | german_data$Personal_Status == "A95"] <- "F"

#adding a new column age category to convert numerical data of age to categorical values converting it into 4 categories YOung middle, age, adults, and seniors.

german_data$Age_Category[german_data$Age < 31] <- "Young"
german_data$Age_Category[german_data$Age >30 & german_data$Age < 41] <- "Middle_Age"
german_data$Age_Category[german_data$Age >40 & german_data$Age < 61] <- "Adults"
german_data$Age_Category[german_data$Age >60] <- "Seniors"

#creating a new data frame of males data and females data to use further
german_data_f <- subset(german_data,Sex == "F")
german_data_m <- subset(german_data,Sex == "M")

#converting numerical data to categorical data for box plot
german_data$Installment_Rate_Cat <- paste("B", german_data$Installment_Rate)

#checking for null values in the data frame
german_df <- as.data.frame(
  cbind(
    lapply(
      lapply(german_data, is.na), sum)
    )
  )
colnames(german_df) <- c('Number of Null Values in Column')
rownames(subset(german_df, german_df$nullvalues != 0))
View(german_df)
#data is clean and doesnt have any null values
```

## Corr Plot to show co relation
```{r}
#Showing correlation between the various numerical values in the data frame
library(corrplot)
df <- select(german_data, Duration, Credit_Amount, Installment_Rate, Age,Existing_Credit,Dependents)
colnames(df) <- c("Duration", "Credit Amount", "Installment Rate", "Age","Existing Credit","Dependents")

corrplot(cor(df[,1:6]), method = "circle", title ="Corrplot for Numerical values", mar = c(0,0,1,0))

```

## Pie Chart depicting number of good bad male female  
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)

df <- german_data %>% 
   group_by(Good_bad, Sex) %>% 
   summarise(Count = n())

ggplot(df, aes(x = "", y = Count ,fill = Good_bad)) + 
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(label = paste(Count,Sex)), position = position_stack(vjust = 0.5), color = "white") +
  scale_fill_manual(values = c("#DB4325","#006164")) +
  coord_polar(theta = "y") +
  labs(title = "Risk Ratio for Genders")

#This pie chart shows that only 1/4 of male credit applicants are classified as bad where as more than 1/3 rd of the female applicants are classified as bad. We are trying to explore whether this is just a bias towards men or if the various attributes are diff in case of males and females
```

## DENSITY PLOT - 2 BOX PLOT 1
```{r}
library(ggplot2)
library(dplyr)

#Density plot of men applicants and age showing that the number of young men being classified as bad risk are slightly more than the number of young men being classified Good risk
pm <- ggplot(german_data_m, aes(Age, fill = Good_bad)) + 
  geom_density(alpha=.5) +
  scale_fill_manual(values = c("#DB4325","#006164")) +
  labs(x = "Age", y = "Density", title = "Age distribution of Males seeking credit") + 
  geom_vline(aes(xintercept=mean(Age)), color="blue", linetype="dashed", size=1)

#Density plot of women applicants and age showing that the number of young females being classified as bad risk is drastically more than the number of young women being classified Good risk

pf <- ggplot(german_data_f, aes(Age, fill= Good_bad)) + 
  geom_density(alpha=.5) +    
  scale_fill_manual(values = c("#DB4325","#006164")) +
  labs(x = "Age", y = "Density", title = "Age distribution of Females seeking credit") + 
  geom_vline(aes(xintercept=mean(Age)), color="blue", linetype="dashed", size=1)

#pyramid plot of everyone's age showing almost equal number of young men and women applying for credit
p <- ggplot(german_data,aes(x=Age ,fill = Sex)) + 
  geom_bar(data=subset(german_data, Sex == "F")) + 
  geom_bar(data=subset(german_data, Sex == "M"),aes(y=..count..*(-1))) + 
  scale_y_continuous(breaks=seq(-40,40,10),labels=abs(seq(-40,40,10))) + 
  scale_fill_manual(values = c("#0C7BDC","#FFC20A")) +
  labs( x= "Gender Distribution", y = "Age", title = "Age distribution of everyone applying for credit") + 
  geom_vline(aes(xintercept=mean(Age)), color="Red", linetype="dashed", size=1)
p
pm
pf

```

## BOX PLOT for Credit Amount
```{r}
library(ggplot2)
p2 <- ggplot(german_data,aes(x = Sex, y = Credit_Amount, fill = Good_bad)) + 
   geom_boxplot() +
   labs(y = "Credit Amount") +
   scale_fill_manual(values = c("#DB4325","#006164")) +
  labs(title = "Credit Amount distribution for both Genders")
p2

```

## Scatter plot for credit amount and duration
```{r}
#Young women take up smaller amounts of loans than men for similar duration but contrary to the above plot the number of women getting rejected in this case are very high as compared to men
ggplot(german_data, aes(x = Duration, y = Credit_Amount, color = Sex)) +
  geom_point() + 
  labs(y = "Credit Amount", title = "Credit Amount vs Duration") +
  geom_smooth(method=lm, se=FALSE, fullrange = TRUE)
```

## Violin Box Plot 
```{r}
library(ggplot2)

ggplot(german_data, aes(x = Installment_Rate_Cat, y = Age, fill = Sex)) + 
  geom_violin() + 
  geom_boxplot(color="Black", width=0.2, position = position_dodge(0.9)) +
    scale_fill_manual(values = c("#0C7BDC","#FFC20A")) +
  labs(x = "Installment Rate", y = "Age") +
  scale_x_discrete(limits = c("B 1","B 2","B 3","B 4"),
                   labels = c("1%", "2%", "3%","4%")) +
  labs(title = "Installment Rate vs Age for both Genders")
  

```

## Stacked bar plot gender vs Property
```{r}
#property vs gender shows us that the percentage of young women having property or building and society savings agreements/life insurances is more than that of men but in the end they are still rejected more
library(ggplot2)
library(dplyr)
df <- german_data%>% 
  subset(Age_Category == "Young") %>%
  group_by(Property, Sex) %>%
  dplyr::summarise(count = n())
ggplot(df, aes(x = Sex, y = count, fill = Property)) + 
geom_bar(stat = "identity", position = "fill") +
  scale_fill_discrete(labels = c("Real Estate", "Insurance", "Car or Other","No Property")) +
    scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0), labels = c("10%","20%","30%","40%","50%","60%","70%","80%","90%","100%")) +
  geom_hline(yintercept = 0.5) +
  labs(title = "Property Distribution", y ="% of Total")



```

## Stacked bar plot for purpose vs gender and Good_bad
```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)

df <- german_data %>%
  group_by(Purpose, Good_bad, Sex) %>%
  dplyr::summarise(count = n())

p4_1 <- ggplot(df, aes(x = Purpose, y = count, fill = Good_bad)) + 
    geom_bar(stat = "identity", position = "fill") +
    scale_fill_manual(values = c("#DB4325","#006164")) +
    labs( y = "% of Total", title = "Total") +
    labs( x = "", title = "")+
 scale_x_discrete(limits = c("A40","A41","A42","A43","A44","A45","A46","A48","A49","A410"),
                  labels = c("Car (New)", "Car (Used)", "Furniture","TV","Appliances","Repairs", "Education", "Retraining", "Business","Others")) +
    scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0), labels = c("10%","20%","30%","40%","50%","60%","70%","80%","90%","100%")) +
  theme(axis.text.x = element_text(angle=90)) +
  labs(title = "Purpose Distribution" )
p4_1

df<- german_data %>% 
  subset(Sex == "F") %>%
  group_by(Purpose,Good_bad) %>%
  dplyr::summarise(count = n())
p4_2 <- ggplot(df, aes(x = Purpose, y = count, fill = Good_bad)) + 
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = c("#DB4325","#006164")) +
  scale_x_discrete(limits = c("A40","A41","A42","A43","A44","A45","A46","A48","A49","A410"),
                   labels = c("Car (New)", "Car (Used)", "Furniture","TV","Appliances","Repairs", "Education", "Retraining", "Business","Others")) +
  scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0), 
                      labels = c("10%","20%","30%","40%","50%","60%","70%","80%","90%","100%")) +
  theme(axis.text.x = element_text(angle = 90))+
  labs( y = "% of Total females", tag = "F")


df<- german_data %>% 
  subset(Sex == "M") %>%
  group_by(Purpose, Good_bad) %>%
  dplyr::summarise(count = n())
p4_3 <- ggplot(df,aes(x = Purpose, y = count, fill = Good_bad)) + 
geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = c("#DB4325","#006164")) + 
  scale_x_discrete(limits = c("A40","A41","A42","A43","A44","A45","A46","A48","A49","A410"),
                   labels = c("Car (New)", "Car (Used)", "Furniture","TV","Appliances","Repairs", "Education", "Retraining", "Business","Others")) +
   scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0), 
                      labels = c("10%","20%","30%","40%","50%","60%","70%","80%","90%","100%")) +
  theme(axis.text.x = element_text(angle=90))+
  labs( y = "% of Total males", tag = "M")


grid.arrange(p4_2,p4_3, ncol =2)

```
